apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    path: app-of-apps
    helm:
      parameters:
      - name: "argocd.giropopsSenhas.enabled"
        value: "true"
      - name: "argocd.randomLogger.enabled"
        value: "true"
    repoURL: https://github.com/felipedsnt/descomplicando-gitops-no-kubernetes-argocd.git
    targetRevision: feat/day2
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true